sudo: false

language: ruby

cache: bundler

services: mongodb

rvm:
  - 2.5.3

before_install:
  - gem update bundler

before_script:
  - bundle exec danger

addons:
  apt:
    packages:
      - mongodb-org-server

env:
  - MONGOID_VERSION=5
  - MONGOID_VERSION=6
  - MONGOID_VERSION=7
  - MONGOID_VERSION=HEAD

matrix:
  include:
    - name: "MongoDB-3.2"
      addons:
        apt:
          sources:
            - mongodb-3.2-trusty
    - name: "MongoDB-3.4"
      addons:
        apt:
          sources:
            - mongodb-3.4-trusty
  allow_failures:
    - env: MONGOID_VERSION=HEAD
